<?xml version="1.0"?>
<robot name="differential_wheeled_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  

  <xacro:include filename="$/urdf/wheel.urdf.xacro" /> 


<!-- Defining the colors used in this robot -->
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="Red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>


  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>



  <!-- PROPERTY LIST -->
  <!--All units in m-kg-s-radians unit system -->
  <property name="M_PI" value="3.1415926535897931" />
  <property name="M_PI_2" value="1.570796327" />
  <property name="DEG_TO_RAD" value="0.017453293" />

  <!-- Main body length, width and height -->
  <!-- Main Body base block  -->
  <property name="base_height" value="0.038" />
  <property name="base_width" value="0.148" />
  <property name="base_length" value="0.189" />
  <property name="base_mass" value="0.44" /> <!-- in kg-->


  <!-- Wheels -->
  <property name="wheel_mass" value="0.054355" /> --> <!-- in kg-->
  
  <property name="base_x_origin_to_wheel_origin" value="0.0" />
  <property name="base_y_origin_to_wheel_origin" value="0.075" />
  <property name="base_z_origin_to_wheel_origin" value="0.0" />


  <!-- Hokuyo Laser scanner -->
  <property name="hokuyo_size" value="0.05" />


  <!-- Macro for calculating inertia of frame -->
  <macro name="frame_inertia" params="m l w h">
    <inertia  ixx="7.206" ixy = "169.4" ixz = "-5.73"
              iyx="-8.953" iyy="2.010" iyz = "-3.059"
              izx="2770" izy="-3.059" izz="2.547" /> 
  </macro>


  <!-- BASE-FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
  <link name="base_footprint">
    <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0" 
          izz="0.0001" />
    </inertial>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius - base_z_origin_to_wheel_origin}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>
  
  <!-- BASE-LINK -->
  <!--Actual body/chassis of the robot-->
  <link name="base_link">
    <inertial>
      <mass value="${base_mass}" />
      <origin xyz="0 0 0" />
      <!--The 3x3 rotational inertia matrix. -->
        <frame_inertia  m="${base_mass}" l="${base_length}" w="${base_width}" h="${base_height}" />

    </inertial>    
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>

          <box length="${base_length}" width="${base_width}" height="${base_height}" />

      </geometry>
      <material name="White" />
    </visual>  
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0 " />
      <geometry>

          <box length="${base_length}" width="${base_width}" height="${base_height}" />

      </geometry>
    </collision>     
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/White</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>


<!-- Wheel Definitions -->

  <wheel fb="front" lr="right" parent="base_link" translateX="116" translateY="-0.056" flipY="1"/>
  <wheel fb="front" lr="left" parent="base_link" translateX="116" translateY="0.056" flipY="1"/>
  <wheel fb="back" lr="right" parent="base_link" translateX="0" translateY="-0.056" flipY="1"/>
  <wheel fb="back" lr="left" parent="base_link" translateX="0" translateY="0.056" flipY="1"/>
	 
  <!-- SENSORS -->
  
  <!-- u0007 STILL NEEDS DEFINING -->

  <link name="u0007_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${u0007_size} ${u0007_size} ${u0007_size}"/>
      </geometry>
      <material name="Black" />
    </visual>
  </link>
  <joint name="u0007_joint" type="fixed">
    <origin xyz="${base_radius - u0007_size/2} 0 ${base_height+u0007_size/4}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="u0007_link" />
  </joint>
  <gazebo reference="u0007_link">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <sensor type="ray" name="head_u0007_sensor">
      <pose>${hokuyo_size/2} 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>10.0</max>
          <resolution>0.001</resolution>
        </range>
      </ray>
      <plugin name="gazebo_ros_head_u0007_controller" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>u0007_link</frameName>
      </plugin>
    </sensor>
  </gazebo>
  
  
  <!-- Differential drive controller  -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">

      <rosDebugLevel>Debug</rosDebugLevel>
      <publishWheelTF>false</publishWheelTF>
      <robotNamespace>/</robotNamespace>
      <publishTf>1</publishTf>
      <publishWheelJointState>false</publishWheelJointState>
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <leftJoint>front_left_wheel_joint</leftJoint>
      <rightJoint>front_right_wheel_joint</rightJoint>
      <wheelSeparation>${2*base_radius}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <broadcastTF>1</broadcastTF>
      <wheelTorque>30</wheelTorque>
      <wheelAcceleration>1.8</wheelAcceleration>
      <commandTopic>cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame> 
      <odometryTopic>odom</odometryTopic> 
      <robotBaseFrame>base_footprint</robotBaseFrame>


    </plugin>
  </gazebo> 




</robot>
